name: AI Agent Workflow

on:
  issues:
    types: [opened, edited, labeled]
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  ai-agent:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      
      - name: AI Agent Response
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const context = github.context;
            let body = '';
            
            if (context.eventName === 'issues') {
              body = `Thanks for opening this issue! I'm Carmen 2.0, your AI assistant. I'll analyze your request and help you out.

              I see you're asking about: ${context.payload.issue.title}
              
              Let me look into this for you...`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: body
              });
            }
            
            if (context.eventName === 'pull_request') {
              body = `Thanks for the pull request! I'll review your changes and provide feedback shortly.`;
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body: body
              });
            }
